---
sidebar: sidebar 
permalink: reference-instance-types.html 
keywords: BlueXP classification, installation, deployment, instance, virtual machine, cpu, ram, memory, disk, capacity 
summary: 'Le logiciel de classification des données doit s"exécuter sur un hôte qui répond aux exigences spécifiques du système d"exploitation, aux exigences de RAM, aux exigences logicielles, etc.  Lors du déploiement de la classification des données dans le cloud, il est recommandé d"utiliser un système doté de caractéristiques « larges » pour une fonctionnalité complète.' 
---
= Types d'instances de NetApp Data Classification pris en charge
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Data Classification doit être exécuté sur un hôte répondant à des exigences spécifiques en matière de système d'exploitation, de mémoire vive (RAM) et de logiciel. Lors du déploiement de Data Classification dans le cloud, nous recommandons d'utiliser un système avec les caractéristiques « large » pour une fonctionnalité complète.

Dans les tableaux suivants, si le système marqué « par défaut » n'est pas disponible dans la région où vous installez Data Classification, le type d'instance suivant indiqué dans le tableau sera déployé.



== Types d'instances AWS

[cols="20,30,25"]
|===
| Taille du système | Spécifications | Type d'instance 


| Très grand | 32 processeurs, 128 Go de RAM, 1 To de SSD gp3 | https://aws.amazon.com/ec2/instance-types/m6i/["m6i.8xlarge"^](défaut) 


| Grand | 16 processeurs, 64 Go de RAM, 500 Go de SSD | https://aws.amazon.com/ec2/instance-types/m6i/["m6i.4xlarge"^](par défaut) m6a.4xlarge m5a.4xlarge m5.4xlarge m4.4xlarge 
|===


== Types d'instances Azure

[cols="20,30,25"]
|===
| Taille du système | Spécifications | Type d'instance 


| Très grand | 16 processeurs, 64 Go de RAM, disque système (2 048 Gio, débit minimal de 250 Mo/s) et disque de données (SSD de 1 Tio, débit minimal de 750 Mo/s) | https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/general-purpose/dv5-series["Standard_D32s_v5 ou Standard_D32_v5"^] 


| Grand | 16 processeurs, 64 Go de RAM, 500 Go de SSD | link:https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/general-purpose/dsv5-series?tabs=sizebasic["Standard_D16_v5 ou Standard_D16s_v5"^] (défaut) 
|===


== Types d'instances GCP

[cols="20,30,25"]
|===
| Taille du système | Spécifications | Type d'instance 


| Grand | 16 processeurs, 64 Go de RAM, 500 Go de SSD | https://cloud.google.com/compute/docs/general-purpose-machines#n2_machines["n2-standard-16"^](par défaut) n2d-standard-16 n1-standard-16 
|===