---
sidebar: sidebar 
permalink: task-deploy-compliance-dark-site.html 
keywords: cloud compliance, bluexp, data sense, get started, web browser connectivity, cloud compliance access, privacy, linux, ubuntu, compliance, on-premises, dark site, upgrade, private mode, docker, podman, rhel, bluexp classification, classification, install, cloud data sense, linux host 
summary: 'Suivez quelques étapes pour installer NetApp Data Classification sur un hôte Linux dans un site local qui n"a pas accès à Internet - également appelé « mode privé ». Ce type d"installation est parfait pour vos sites sécurisés.' 
---
= Installer NetApp Data Classification sur un hôte Linux sans accès Internet
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
L'installation de NetApp Data Classification sur un hôte Linux dans un site local qui n'a pas accès à Internet est appelée _mode privé_.  Ce type d’installation, qui utilise un script d’installation, n’a aucune connectivité à la couche SaaS de la NetApp Console .


IMPORTANT: Le mode privé BlueXP (interface BlueXP héritée) est généralement utilisé avec des environnements locaux qui n’ont pas de connexion Internet et avec des régions cloud sécurisées, notamment AWS Secret Cloud, AWS Top Secret Cloud et Azure IL6. NetApp continue de prendre en charge ces environnements avec l’interface BlueXP héritée. Pour la documentation du mode privé dans l'ancienne interface BlueXP , voirlink:https://docs.netapp.com/us-en/console-setup-admin/media/BlueXP-Private-Mode-legacy-interface.pdf["Documentation PDF pour le mode privé BlueXP"^] .
