---
sidebar: sidebar 
permalink: task-scanning-overview.html 
keywords: cloud compliance, get started, enable cloud compliance, cifs credentials, smb credentials, cloud compliance access, privacy, compliance, dp volumes, data protection volumes, CVO, Cloud Volumes ONTAP, data sense, cloud data sense, map-only scans, map and classify, full 
summary: Analysez vos sources de données avec NetApp Data Classification. 
---
= Analyser les sources de données avec la NetApp Data Classification
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Data Classification analyse les données dans les référentiels (les volumes, les schémas de base de données ou autres données utilisateur) que vous sélectionnez afin d'identifier les données personnelles et sensibles. Data Classification cartographie ensuite les données de votre organisation, catégorise chaque fichier et identifie les modèles prédéfinis dans les données. Le résultat de l'analyse est un index des informations personnelles, des informations personnelles sensibles, des catégories de données et des types de fichiers.

Après l'analyse initiale, Data Classification analyse en continu vos données de manière circulaire pour détecter les modifications incrémentielles.  C'est pourquoi il est important de maintenir l'instance en cours d'exécution.

Vous pouvez activer et désactiver les analyses au niveau du volume ou au niveau du schéma de base de données.



[[understand-scan-types]]
== Comprendre les types de scan

Vous pouvez effectuer deux types d’analyses dans la classification des données :

* **Les analyses cartographiques uniquement** offrent un aperçu général de vos données et sont effectuées sur des sources de données sélectionnées. Les analyses cartographiques uniquement prennent moins de temps que les analyses complètes car elles n'accèdent pas aux fichiers pour voir les données à l'intérieur.
* **L'analyse complète** permet une analyse approfondie de vos données. Une analyse complète inclut une analyse de cartographie et une classification des données à l'intérieur des fichiers.



TIP: Effectuer une analyse cartographique uniquement peut être utile pour obtenir une vue d'ensemble de vos données et identifier des zones spécifiques sur lesquelles effectuer des analyses complètes.

Consultez les tableaux pour voir quelles informations apparaissent dans les analyses uniquement par carte et dans les analyses complètes.

[cols="47,18,18"]
|===
| Fonctionnalité | Scan complet | Analyse uniquement de la carte 


| Vitesse de numérisation | Lent | Rapide 


| Tarifs | Gratuit | Gratuit 


| Capacité | Limité à 500 Tio* | Limité à 500 Tio* 


| Liste des types de fichiers et de la capacité utilisée | Oui | Oui 


| Nombre de fichiers et capacité utilisée | Oui | Oui 


| Âge et taille des fichiers | Oui | Oui 


| Capacité à exécuter unlink:task-controlling-governance-data.html["Rapport de mappage des données"] | Oui | Oui 


| Page d'enquête sur les données pour afficher les détails du fichier | Oui | Non 


| Rechercher des noms dans les fichiers | Oui | Non 


| Créerlink:task-using-policies.html["requêtes enregistrées"] qui fournissent des résultats de recherche personnalisés | Oui | Non 


| Possibilité d'exécuter d'autres rapports | Oui | Non 


| Possibilité de voir les métadonnées des fichiers** | Oui | Oui 
|===
{asterisk}La classification des données ne limite pas la quantité de données qu'elle analyse. Chaque agent Console prend en charge l'analyse et l'affichage de 500 Tio de données. Pour analyser plus de 500 Tio de données, link:https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html#connector-installation["installer un autre agent de console"^] puis link:task-deploy-overview.html["déployer une autre instance de classification des données"]. L'interface utilisateur de la Console affiche les données d'un seul connecteur. Pour obtenir des conseils sur l'affichage des données provenant de plusieurs agents Console, voir link:https://docs.netapp.com/us-en/console-setup-admin/task-manage-multiple-connectors.html#switch-between-connectors["Travailler avec plusieurs agents de console"^].

{asterisk}{asterisk} Les métadonnées suivantes sont extraites des fichiers lors des analyses de mappage :

* Heure de découverte du fichier
* Dernière consultation du fichier
* Fichier modifié pour la dernière fois
* Type de fichier
* Taille du fichier
* Création de fichier
* Nombre de fichiers
* Extraction des autorisations
* Référentiel de stockage
* Système
* Type de système
* Capacité utilisée


.Différences entre les tableaux de bord de gouvernance :
[%collapsible]
====
[cols="40,25,25"]
|===
| Fonctionnalité | Scan complet | Analyse uniquement de la carte 


| Données obsolètes | Oui | Oui 


| Données non commerciales | Oui | Oui 


| Fichiers dupliqués | Oui | Oui 


| Requêtes enregistrées prédéfinies | Oui | Non 


| Requêtes enregistrées par défaut | Oui | Oui 


| Rapport DDA | Oui | Oui 


| Rapport de cartographie | Oui | Oui 


| Détection du niveau de sensibilité | Oui | Non 


| Données sensibles avec des autorisations étendues | Oui | Non 


| Autorisations ouvertes | Oui | Oui 


| L'âge des données | Oui | Oui 


| Taille des données | Oui | Oui 


| Catégories | Oui | Non 


| Types de fichiers | Oui | Oui 
|===
====
.Différences entre les tableaux de bord de conformité :
[%collapsible]
====
[cols="40,25,25"]
|===
| Fonctionnalité | Scan complet | Analyse uniquement de la carte 


| Informations personnelles | Oui | Non 


| Informations personnelles sensibles | Oui | Non 


| Rapport d'évaluation des risques liés à la vie privée | Oui | Non 


| Rapport HIPAA | Oui | Non 


| Rapport PCI DSS | Oui | Non 
|===
====
.Différences entre les filtres d'investigation :
[%collapsible]
====
[cols="40,25,25"]
|===
| Fonctionnalité | Scan complet | Analyse uniquement de la carte 


| Requêtes enregistrées | Oui | Oui 


| Type de système | Oui | Oui 


| Système | Oui | Oui 


| Référentiel de stockage | Oui | Oui 


| Type de fichier | Oui | Oui 


| Taille du fichier | Oui | Oui 


| Temps de création | Oui | Oui 


| Temps découvert | Oui | Oui 


| Dernière modification | Oui | Oui 


| Dernier accès | Oui | Oui 


| Autorisations ouvertes | Oui | Oui 


| Chemin du répertoire de fichiers | Oui | Oui 


| Catégorie | Oui | Non 


| Niveau de sensibilité | Oui | Non 


| Nombre d'identifiants | Oui | Non 


| Données personnelles | Oui | Non 


| Données personnelles sensibles | Oui | Non 


| Personne concernée | Oui | Non 


| Doublons | Oui | Oui 


| Statut de classification | Oui | Le statut est toujours « Informations limitées » 


| Événement d'analyse d'analyse | Oui | Oui 


| Hachage de fichier | Oui | Oui 


| Nombre d'utilisateurs avec accès | Oui | Oui 


| Autorisations utilisateur/groupe | Oui | Oui 


| Propriétaire du fichier | Oui | Oui 


| Type de répertoire | Oui | Oui 
|===
====