---
sidebar: sidebar 
permalink: task-deploy-overview.html 
keywords: cloud compliance, data sense, get started, deploy cloud data sense, outbound internet, endpoints, cloud compliance internet, web browser connectivity, cloud compliance access, privacy, compliance, bluexp classification 
summary: Planifiez le déploiement de NetApp Data Classification qui répond à vos besoins. 
---
= Choisissez votre méthode de déploiement NetApp Data Classification
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez déployer la NetApp Data Classification de différentes manières. Examinez les méthodes disponibles afin de choisir celle qui correspond le mieux à vos besoins.

* link:task-deploy-cloud-compliance.html["Déployer dans le cloud à l'aide de la console"] . La console déploie l’instance de classification des données dans le même réseau de fournisseur de cloud que l’agent de la console.
* link:task-deploy-compliance-onprem.html["Installer sur un hôte Linux avec accès Internet"] . Installez Data Classification sur un hôte Linux de votre réseau ou sur un hôte Linux dans le cloud, disposant d'un accès Internet.  Ce type d'installation peut être une bonne option si vous préférez analyser les systèmes ONTAP sur site à l'aide d'une instance de classification des données également située sur site, bien que cela ne soit pas une exigence.
* link:task-deploy-compliance-dark-site.html["Installer sur un hôte Linux dans un site sur site sans accès Internet"], également connu sous le nom de _mode privé_. Ce type d'installation, qui utilise un script d'installation, n'a aucune connectivité à la couche SaaS de la console.



TIP: Pour les déploiements VMware sur site vSphere, la classification des données prend en charge une version simplifiée link:task-deploy-ova.html["déploiement avec OVA"].



[[on-premises-installation-script]]
== Script d'installation sur site

L'installation, qu'elle soit réalisée sur un hôte Linux avec accès Internet ou sur un hôte Linux local sans accès Internet, utilise un script d'installation. Le script commence par vérifier si le système et l'environnement répondent aux prérequis. Si les prérequis sont remplis, l'installation démarre.

Un logiciel distinct permet de vérifier la compatibilité de votre système Linux. Pour exécuter ce logiciel de vérification, consultez link:task-test-linux-system.html["Vérifiez que votre système Linux est prêt à installer Data Classification"].
