---
sidebar: sidebar 
permalink: task-test-linux-system.html 
keywords: cloud compliance, bluexp, data sense, get started, deploy, data classification, cloud compliance access, compliance, on-premises, linux, test linux system, docker, podman, ubuntu, rhel, dark site 
summary: 'Avant d"installer Data Classification manuellement sur un hôte Linux, vous pouvez exécuter un script sur l"hôte pour vérifier que toutes les conditions préalables sont en place pour l"installation de Data Classification.  Vous pouvez exécuter ce script sur un hôte Linux de votre réseau ou sur un hôte Linux dans le cloud.  L"hôte peut être connecté à Internet ou résider sur un site qui n"a pas accès à Internet.' 
---
= Vérifiez que votre hôte Linux est prêt à installer NetApp Data Classification
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avant d'installer manuellement NetApp Data Classification sur un hôte Linux, exécutez éventuellement un script sur l'hôte pour vérifier que toutes les conditions préalables sont réunies pour l'installation de Data Classification.  Vous pouvez exécuter ce script sur un hôte Linux de votre réseau ou sur un hôte Linux dans le cloud.  L'hôte peut être connecté à Internet ou résider sur un site qui n'a pas accès à Internet (un _site sombre_).

Il existe également un script de test prérequis qui fait partie du script d'installation de la classification des données.  Le script décrit ici est spécifiquement conçu pour les utilisateurs qui souhaitent vérifier l'hôte Linux indépendamment de l'exécution du script d'installation de la classification des données.



== Commencer

Vous effectuerez les tâches suivantes.

. Vous pouvez également installer un agent de console si vous n'en avez pas déjà un installé.  Vous pouvez exécuter le script de test sans avoir installé d'agent de console, mais le script vérifie la connectivité entre l'agent de console et la machine hôte de classification des données. Il est donc recommandé de disposer d'un agent de console.
. Préparez la machine hôte et vérifiez qu’elle répond à toutes les exigences.
. Activez l'accès Internet sortant à partir de la machine hôte de classification des données.
. Vérifiez que tous les ports requis sont activés sur tous les systèmes.
. Téléchargez et exécutez le script de test prérequis.




== Créer un agent de console

Un agent de console est requis avant de pouvoir installer et utiliser la classification des données.  Vous pouvez toutefois exécuter le script Prérequis sans agent de console.

Tu peux https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-on-prem.html["installer l'agent de console sur site"^] sur un hôte Linux de votre réseau ou sur un hôte Linux dans le cloud.  Certains utilisateurs prévoyant d’installer la classification des données sur site peuvent également choisir d’installer l’agent de console sur site.

Pour créer un agent de console dans votre environnement de fournisseur de cloud, consultez https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-aws.html["création d'un agent de console dans AWS"^] , https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-azure.html["création d'un agent de console dans Azure"^] , ou https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-google.html["création d'un agent de console dans GCP"^] .

Vous aurez besoin de l'adresse IP ou du nom d'hôte du système d'agent de la console lors de l'exécution du script Prérequis.  Vous disposerez de ces informations si vous avez installé l'agent Console dans vos locaux.  Si l'agent Console est déployé dans le cloud, vous pouvez trouver ces informations depuis la Console : sélectionnez l'icône Aide puis *Support* puis *Agent Console*.



== Vérifier les exigences de l'hôte

Le logiciel de classification des données doit s'exécuter sur un hôte qui répond aux exigences spécifiques du système d'exploitation, aux exigences de RAM, aux exigences logicielles, etc.

* La classification des données n'est pas prise en charge sur un hôte partagé avec d'autres applications : l'hôte doit être un hôte dédié.
* Lors de la création du système hôte dans vos locaux, vous pouvez choisir parmi ces tailles de système en fonction de la taille de l'ensemble de données que vous prévoyez d'analyser pour la classification des données.
+
[cols="17,17,27,31"]
|===
| Taille du système | processeur | RAM (la mémoire d'échange doit être désactivée) | Disque 


| *Extra Large* | 32 processeurs | 128 Go de RAM  a| 
** 1 Tio SSD sur /, ou 100 Gio disponibles sur /opt
** 895 Gio disponibles sur /var/lib/docker
** 5 Gio sur /tmp
** *Pour Podman, 30 Go sur /var/tmp*




| *Grand* | 16 processeurs | 64 Go de RAM  a| 
** 500 Gio SSD sur /, ou 100 Gio disponibles sur /opt
** 400 Gio disponibles sur /var/lib/docker ou pour Podman /var/lib/containers
** 5 Gio sur /tmp
** *Pour Podman, 30 Go sur /var/tmp*


|===
* Lors du déploiement d'une instance de calcul dans le cloud pour votre installation de classification des données, il est recommandé d'utiliser un système qui répond aux exigences système « Large » ci-dessus :
+
** *Type d'instance Amazon Elastic Compute Cloud (Amazon EC2)* : « m6i.4xlarge ». link:reference-instance-types.html#aws-instance-types["Voir d'autres types d'instances AWS"^] .
** *Taille de la machine virtuelle Azure* : « Standard_D16s_v3 ». link:reference-instance-types.html#azure-instance-types["Voir d'autres types d'instances Azure"^] .
** *Type de machine GCP* : « n2-standard-16 ». link:reference-instance-types.html#gcp-instance-types["Voir les types d'instances GCP supplémentaires"^] .


* *Autorisations de dossier UNIX* : Les autorisations UNIX minimales suivantes sont requises :
+
[cols="25,25"]
|===
| Dossier | Autorisations minimales 


| /tmp | `rwxrwxrwt` 


| /opter | `rwxr-xr-x` 


| /var/lib/docker | `rwx------` 


| /usr/lib/systemd/système | `rwxr-xr-x` 
|===
* *Système opérateur*:
+
** Les systèmes d’exploitation suivants nécessitent l’utilisation du moteur de conteneur Docker :
+
*** Red Hat Enterprise Linux versions 7.8 et 7.9
*** Ubuntu 22.04 (nécessite la version 1.23 ou supérieure de Data Classification)
*** Ubuntu 24.04 (nécessite la version 1.23 ou supérieure de Data Classification)


** Les systèmes d'exploitation suivants nécessitent l'utilisation du moteur de conteneur Podman et nécessitent la version 1.30 ou supérieure de Data Classification :
+
*** Red Hat Enterprise Linux versions 8.8, 8.10, 9.0, 9.1, 9.2, 9.3, 9.4, 9.5 et 9.6.


** Les extensions vectorielles avancées (AVX2) doivent être activées sur le système hôte.


* *Red Hat Subscription Management* : L'hôte doit être enregistré auprès de Red Hat Subscription Management.  S'il n'est pas enregistré, le système ne peut pas accéder aux référentiels pour mettre à jour les logiciels tiers requis lors de l'installation.
* *Logiciel supplémentaire* : Vous devez installer le logiciel suivant sur l'hôte avant d'installer Data Classification :
+
** Selon le système d'exploitation que vous utilisez, vous devrez installer l'un des moteurs de conteneur :
+
*** Docker Engine version 19.3.1 ou supérieure. https://docs.docker.com/engine/install/["Voir les instructions d'installation"^] .
*** Podman version 4 ou supérieure.  Pour installer Podman, entrez(`sudo yum install podman netavark -y` ).






* Version Python 3.6 ou supérieure. https://www.python.org/downloads/["Voir les instructions d'installation"^] .
+
** *Considérations NTP* : NetApp recommande de configurer le système de classification des données pour utiliser un service NTP (Network Time Protocol).  L'heure doit être synchronisée entre le système de classification des données et le système d'agent de la console.




* *Considérations relatives au pare-feu* : Si vous envisagez d'utiliser `firewalld` , nous vous recommandons de l'activer avant d'installer Data Classification.  Exécutez les commandes suivantes pour configurer `firewalld` afin qu'il soit compatible avec la classification des données :
+
....
firewall-cmd --permanent --add-service=http
firewall-cmd --permanent --add-service=https
firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --permanent --add-port=8080/tcp
firewall-cmd --permanent --add-port=443/tcp
firewall-cmd --reload
....
+
Si vous prévoyez d'utiliser des hôtes de classification de données supplémentaires comme nœuds de scanner (dans un modèle distribué), ajoutez ces règles à votre système principal à ce stade :

+
....
firewall-cmd --permanent --add-port=2377/tcp
firewall-cmd --permanent --add-port=7946/udp
firewall-cmd --permanent --add-port=7946/tcp
firewall-cmd --permanent --add-port=4789/udp
....
+
Notez que vous devez redémarrer Docker ou Podman chaque fois que vous activez ou mettez à jour `firewalld` paramètres.





== Activer l'accès Internet sortant à partir de la classification des données

La classification des données nécessite un accès Internet sortant.  Si votre réseau virtuel ou physique utilise un serveur proxy pour l'accès à Internet, assurez-vous que l'instance de classification des données dispose d'un accès Internet sortant pour contacter les points de terminaison suivants.


TIP: Cette section n'est pas requise pour les systèmes hôtes installés sur des sites sans connectivité Internet.

[cols="43,57"]
|===
| Points de terminaison | But 


| \ https://api.bluexp.netapp.com | Communication avec le service Console, qui inclut les comptes NetApp . 


| \ https://netapp-cloud-account.auth0.com \ https://auth0.com | Communication avec le site Web de la console pour l'authentification centralisée des utilisateurs. 


| \ https://support.compliance.api.bluexp.netapp.com/ \ https://hub.docker.com \ https://auth.docker.io \ https://registry-1.docker.io \ https://index.docker.io/ \ https://dseasb33srnrn.cloudfront.net/ \ https://production.cloudflare.docker.com/ | Fournit un accès aux images logicielles, aux manifestes, aux modèles et permet d'envoyer des journaux et des métriques. 


| \ https://support.compliance.api.bluexp.netapp.com/ | Permet à NetApp de diffuser des données à partir des enregistrements d'audit. 


| \ https://github.com/docker \ https://download.docker.com | Fournit des packages prérequis pour l'installation de Docker. 


| \ http://packages.ubuntu.com/ \ http://archive.ubuntu.com | Fournit des packages prérequis pour l'installation d'Ubuntu. 
|===


== Vérifiez que tous les ports requis sont activés

Vous devez vous assurer que tous les ports requis sont ouverts pour la communication entre l'agent de console, la classification des données, Active Directory et vos sources de données.

[cols="25,25,50"]
|===
| Type de connexion | Ports | Description 


| Agent de console <> Classification des données | 8080 (TCP), 443 (TCP) et 80. 9000 | Les règles de pare-feu ou de routage de l'agent de console doivent autoriser le trafic entrant et sortant sur le port 443 vers et depuis l'instance de classification des données.  Assurez-vous que le port 8080 est ouvert afin de pouvoir voir la progression de l'installation dans la console.  Si un pare-feu est utilisé sur l'hôte Linux, le port 9000 est requis pour les processus internes au sein d'un serveur Ubuntu. 


| Agent de console <> cluster ONTAP (NAS) | 443 (TCP)  a| 
La console découvre les clusters ONTAP à l'aide de HTTPS. Si vous utilisez des stratégies de pare-feu personnalisées, l’hôte de l’agent de console doit autoriser l’accès HTTPS sortant via le port 443.  Si l'agent de la console est dans le cloud, toutes les communications sortantes sont autorisées par le pare-feu prédéfini ou les règles de routage.

|===


== Exécutez le script des prérequis de classification des données

Suivez ces étapes pour exécuter le script des prérequis de classification des données.

https://youtu.be/5ONowfPWkFs?si=QLGUw8mqPrz9qs4B["Regardez cette vidéo"^]pour voir comment exécuter le script Prérequis et interpréter les résultats.

.Avant de commencer
* Vérifiez que votre système Linux répond aux<<Vérifier les exigences de l'hôte,exigences de l'hôte>> .
* Vérifiez que le système dispose des deux packages logiciels prérequis installés (Docker Engine ou Podman et Python 3).
* Assurez-vous que vous disposez des privilèges root sur le système Linux.


.Étapes
. Téléchargez le script des prérequis de classification des données à partir du https://mysupport.netapp.com/site/products/all/details/cloud-data-sense/downloads-tab/["Site de support NetApp"^] .  Le fichier que vous devez sélectionner est nommé *standalone-pre-requisite-tester-<version>*.
. Copiez le fichier sur l’hôte Linux que vous prévoyez d’utiliser (en utilisant `scp` ou une autre méthode).
. Attribuer des autorisations pour exécuter le script.
+
[source, cli]
----
chmod +x standalone-pre-requisite-tester-v1.25.0
----
. Exécutez le script à l’aide de la commande suivante.
+
[source, cli]
----
 ./standalone-pre-requisite-tester-v1.25.0 <--darksite>
----
+
Ajoutez l'option « --darksite » uniquement si vous exécutez le script sur un hôte qui n'a pas accès à Internet.  Certains tests prérequis sont ignorés lorsque l'hôte n'est pas connecté à Internet.

. Le script vous demande l'adresse IP de la machine hôte de classification des données.
+
** Entrez l'adresse IP ou le nom d'hôte.


. Le script vous demande si vous avez installé un agent de console.
+
** Entrez *N* si vous n’avez pas d’agent de console installé.
** Entrez *Y* si vous avez un agent de console installé.  Ensuite, entrez l’adresse IP ou le nom d’hôte de l’agent de la console afin que le script de test puisse tester cette connectivité.


. Le script exécute une variété de tests sur le système et affiche les résultats au fur et à mesure de sa progression.  Une fois terminé, il écrit un journal de la session dans un fichier nommé `prerequisites-test-<timestamp>.log` dans le répertoire `/opt/netapp/install_logs` .


.Résultat
Si tous les tests prérequis se sont déroulés avec succès, vous pouvez installer Data Classification sur l'hôte lorsque vous êtes prêt.

Si des problèmes sont détectés, ils sont classés comme « Recommandé » ou « Obligatoire » pour être résolus.  Les problèmes recommandés sont généralement des éléments qui ralentiraient l'exécution des tâches d'analyse et de catégorisation de la classification des données.  Ces éléments n’ont pas besoin d’être corrigés, mais vous souhaiterez peut-être les corriger.

Si vous rencontrez des problèmes « obligatoires », vous devez les résoudre et exécuter à nouveau le script de test des prérequis.
