= Version 1.42
:allow-uri-read: 




=== Version 1.42

Cette version de BlueXP classification comprend :

.Analyse en masse pour les environnements de travail
La BlueXP classification prend en charge les opérations en masse pour les environnements de travail.  Vous pouvez choisir d'activer les analyses de mappage, d'activer les analyses de mappage et de classification, de désactiver les analyses ou de créer une configuration personnalisée sur les volumes dans l'environnement de travail.  Si vous effectuez une sélection pour un volume individuel, elle remplace la sélection en bloc.  Pour effectuer une opération en masse, accédez à la page **Configuration** et faites votre sélection.

.Télécharger le rapport d'enquête localement
La BlueXP classification prend en charge la possibilité de télécharger des rapports d'enquête sur les données localement pour les afficher dans le navigateur.  Si vous choisissez l'option locale, l'enquête sur les données n'est disponible qu'au format CSV et n'affiche que les 10 000 premières lignes de données.

Pour plus d'informations, consultez la section link:https://docs.netapp.com/us-en/data-services-data-classification/task-investigate-data.html#create-the-data-investigation-report["Examinez les données stockées dans votre organisation avec la BlueXP classification"] .
