= Version 1.44
:allow-uri-read: 




=== Version 1.44

Cette version de BlueXP classification comprend :

.Amélioration des temps de mise à jour du tableau de bord de gouvernance
Les temps de mise à jour des composants individuels du tableau de bord de gouvernance ont été améliorés. Le tableau suivant affiche la fréquence des mises à jour pour chaque composant.

[cols="1,1"]
|===
| Composant | Heures de mise à jour 


| L'ère des données | 24 heures 


| Catégories | 24 heures 


| Aperçu des données | 5 minutes 


| Fichiers en double | 2 heures 


| Types de fichiers | 24 heures 


| Données non commerciales | 2 heures 


| Autorisations d'ouverture | 24 heures 


| Recherches enregistrées | 2 heures 


| Données sensibles et autorisations étendues | 24 heures 


| Taille des données | 24 heures 


| Données obsolètes | 2 heures 


| Principaux référentiels de données par niveau de sensibilité | 2 heures 
|===
Vous pouvez afficher l'heure de la dernière mise à jour et mettre à jour manuellement les composants Fichiers en double, Données non commerciales, Recherches enregistrées, Données obsolètes et Principaux référentiels de données par niveau de sensibilité. Pour plus d'informations sur le tableau de bord de gouvernance, voirlink:https://docs.netapp.com/us-en/data-services-data-classification/task-controlling-governance-data.html["Afficher les détails de gouvernance sur les données stockées dans votre organisation"] .

.Améliorations des performances et de la sécurité
Des améliorations ont été apportées pour améliorer les performances, la consommation de mémoire et la sécurité de la classification BlueXP .

.Corrections de bugs
Redis a été mis à niveau pour améliorer la fiabilité de la BlueXP classification. La BlueXP classification utilise désormais Elasticsearch pour améliorer la précision des rapports sur le nombre de fichiers lors des analyses.
