= Version 1.43
:allow-uri-read: 




=== Version 1.43

Cette version de classification des données comprend :

.Prioriser les analyses de classification
La classification des données prend en charge la possibilité de hiérarchiser les analyses de cartographie et de classification en plus des analyses de cartographie uniquement, vous permettant de sélectionner les analyses à effectuer en premier. La priorisation des analyses Map & Classify est prise en charge pendant et avant le début des analyses. Si vous choisissez de donner la priorité à une analyse pendant qu'elle est en cours, les analyses de mappage et de classification sont toutes deux prioritaires.

Pour plus d'informations, consultez la section link:https://docs.netapp.com/us-en/data-services-data-classification/task-managing-repo-scanning.html#prioritize-scans["Prioriser les analyses"] .

.Prise en charge des catégories de données d'informations personnelles identifiables (PII) canadiennes
Les analyses de classification des données identifient les catégories de données PII canadiennes. Ces catégories comprennent les renseignements bancaires, les numéros de passeport, les numéros d’assurance sociale, les numéros de permis de conduire et les numéros de carte d’assurance-maladie pour toutes les provinces et tous les territoires canadiens.

Pour plus d'informations, consultez la section link:https://docs.netapp.com/us-en/data-services-data-classification/reference-private-data-categories.html#types-of-personal-data["Catégories de données personnelles"] .

.Classification personnalisée (aperçu)
La classification des données prend en charge les classifications personnalisées pour les analyses Map & Classify. Grâce aux classifications personnalisées, vous pouvez personnaliser les analyses de classification des données pour capturer des données spécifiques à votre organisation à l'aide d'expressions régulières. Cette fonctionnalité est actuellement en version préliminaire.

Pour plus d'informations, consultez la section link:https://docs.netapp.com/us-en/data-services-data-classification/task-custom-classification.html["Ajouter des classifications personnalisées"] .

.Onglet Recherches enregistrées
L'onglet **Politiques** a été renommélink:https://docs.netapp.com/us-en/data-services-data-classification/task-using-policies.html["**Recherches enregistrées**"] . La fonctionnalité reste inchangée.

.Envoyer les événements d'analyse à la page Audit
La classification des données prend en charge l'envoi d'événements de classification (lorsqu'une analyse est lancée et lorsqu'elle se termine) aulink:https://docs.netapp.com/us-en/console-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline["Page d'audit du conseil NetApp"^] .

.Mises à jour de sécurité
* Le package Keras a été mis à jour, atténuant les vulnérabilités (BDSA-2025-0107 et BDSA-2025-1984).
* La configuration des conteneurs Docker a été mise à jour. Le conteneur n'a plus accès aux interfaces réseau de l'hôte pour créer des paquets réseau bruts. En réduisant les accès inutiles, la mise à jour atténue les risques potentiels de sécurité.


.Améliorations des performances
Des améliorations de code ont été implémentées pour réduire l’utilisation de la RAM et améliorer les performances globales de la classification des données.

.Corrections de bugs
Les bugs qui entraînaient l'échec des analyses StorageGRID , le non-chargement des options de filtrage de la page d'investigation et le non-téléchargement de l'évaluation de découverte de données pour les évaluations à volume élevé ont été corrigés.
